[package]
edition = "2021"
name = "delag_core"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
tokio = { version = "1.27.0", features = ["full"] }
futures-core = { version = "0.3.17", default-features = false, features = [
  "alloc",
] }
futures-util = { version = "0.3.17", default-features = false, features = [
  "alloc",
] }

# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.0", default-features = false, features = [
  "tokio_fs",
  "napi8",
  "tokio_rt",
  "serde-json",
  "async",
  "experimental",
  "latin1",
  "chrono_date",
  "compat-mode",
  "async",
] }
napi-sys = "2.2.3"
napi-derive = "2.12.2"
actix-web = "4.3.1"
actix-http = "3.3.1"
actix-server = "2.2.0"
serde_json = "1"
actix-files = "0.6.2"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
