/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsResponse {
  data: string
  headers: Record<string, any>
}
export function startServer(callback: (...args: any[]) => any): object
